### ISSUE TITLE
Permissions needed for HAVVO folder ?

### ISSUE THREAD

**Issue by SkybuckFlying** [SMFTricks/Havvo#2]
After SMF Large Upgrade to 2.1.2 I notice the HAVVO theme folder having different permissions than the FUSION theme folder.

I am not sure what the original HAVVO theme folder permissions were.

It would make sense to me that the HAVVO theme in 2.0.X needed "execute" permissions because it contains javascript files.

It seems the FUSION theme and Text Editor of SMS 2.1.3 is causing icons in the text editor to not be displayed.

One icon related file is not loaded for some reason... possibly different folder permissions, not sure.

What do you know about this and permissions for theme folders and files ???

http://www.skybuck.org/PascalCoin/Forum/index.php?topic=3548.0

I will try the suggested code fix first, if that not work then I will have to look further into this... possibly related to permissions...

1. Code fix did not work.
2. Changing permissions did not work. (Permissions changed back, I hope I did it right =D theme folders 755, just clicking filezilla gui was not enough had to put in value manually for some unknown reason to me...)

What a mystery...

**Comment by DiegoAndresCortes** [comment]
Likely unrelated to this theme.
Verify your files or try asking in the support topic for the Fusion theme.
At least 2 icons were added in patches after 2.1.1 which is the last version Fusion has marked as compatible, it might be missing little things from patches.

**Comment by SkybuckFlying** [comment]
The solution was to disable: "minimize javascript and css" somewhere in SMF settings ! ;)
